#!/bin/sh
name="ldconfig"
ldconfig_command="/sbin/ldconfig"

err () {
	exitval=$1
	shift
	echo "$*"
	exit $exitval
}

init_ruby_path()
{
	FIND_PATH="${DIR}/lib/ruby"

	[ ! -d "${FIND_PATH}" ] && err 1 "Unable to find ${FIND_PATH}"

	RUBY_DIR=$( find ${FIND_PATH}/*.*/ -type f -name json.rb -depth 1 -maxdepth 1 -exec dirname {} \; 2>/dev/null )

	[ -z "${RUBY_DIR}" ] && err 1 "Unable to locate json.rb"
	RUBY_PLATFORM_DIR=$( find ${RUBY_DIR}/*-freebsd*/ -type f -name rbconfig.rb -depth 1 -maxdepth 1 -exec dirname {} \; )

	[ -z "${RUBY_PLATFORM_DIR}" ] && err 1 "Unable to locate rbconfig.rb"

	RUBY_VER=$( basename ${RUBY_DIR} )

	[ -z "${RUBY_VER}" ] && err 1 "Unable to determine ruby ver by dir path"
}

ldconfig_start()
{
	local _files _ins

	_ins=
	ldconfig=${ldconfig_command}
	if [ -x "${ldconfig_command}" ]; then
		_LDC="/lib /usr/lib"
		for i in ${ldconfig_local_dirs}; do
			if [ -d "${i}" ]; then
				_files=$( find ${i} -type f )
				if [ -n "${_files}" ]; then
					ldconfig_paths="${ldconfig_paths} `cat ${_files} | sort -u`"
				fi
			fi
		done
		for i in ${ldconfig_paths} /etc/ld-elf.so.conf; do
			if [ -r "${i}" ]; then
				_LDC="${_LDC} ${i}"
			fi
		done
		${ldconfig} -elf ${_ins} ${_LDC}
	fi
}

#
#### # WITH local puppet: ###
#if [ ! -x /usr/local/bin/puppet ]; then
#	env ASSUME_ALWAYS_YES=yes pkg install -y sysutils/puppet6
#fi
#
## run it twice
#/usr/local/bin/puppet apply --hiera_config /usr/local/etc/puppet/hiera.yaml --color false --modulepath=/usr/local/etc/puppet/modules $@
#/usr/local/bin/puppet apply --hiera_config /usr/local/etc/puppet/hiera.yaml --color false --modulepath=/usr/local/etc/puppet/modules $@

#exit 0

#### OLD method ###
if [ "${1}" = "debug" ]; then
	shift
	debug_args="debug"
else
	debug_args="crit"
fi

DIR="/tmp/puppet"
init_ruby_path

GEM_PATH="${DIR}/lib/ruby/${RUBY_VER}/:${DIR}/:${DIR}/bin/:${RUBY_PLATFORM_DIR}/:${DIR}/lib/ruby/site_ruby/${RUBY_VER}/:${DIR}/PPP/lib/ruby/vendor_ruby"
GEM_HOME="${DIR}/lib/ruby/${RUBY_VER}/:${RUBY_PLATFORM_DIR}/:${DIR}/lib/ruby/site_ruby/${RUBY_VER}/:${DIR}/PPP/lib/ruby/vendor_ruby"
#modulepath="${DIR}/etc/puppet/environments/production/modules"
modulepath="/tmp/cbsdpuppet/modules/public"

ldconfig_paths="${DIR}/lib /usr/local/lib"
#
ldconfig_start
#
#"${DIR}/bin/ruby" -I "${DIR}/lib/ruby/${RUBY_VER}/" -I "${DIR}/bin/" -I "${RUBY_PLATFORM_DIR}" -I "${DIR}/lib/ruby/site_ruby/${RUBY_VER}/" ${DIR}/bin/puppet config set hiera_config /tmp/puppet/etc/puppet/hiera.yaml
#"${DIR}/bin/ruby" -I "${DIR}/lib/ruby/${RUBY_VER}/" -I "${DIR}/bin/" -I "${RUBY_PLATFORM_DIR}" -I "${DIR}/lib/ruby/site_ruby/${RUBY_VER}/" ${DIR}/bin/puppet apply --color false --modulepath=${modulepath} $@
export PATH=${DIR}/bin:${DIR}/sbin:$PATH
#facter
#echo "${DIR}/bin/ruby -I/tmp/puppet/lib/ruby/vendor_ruby -I ${DIR}/lib/ruby/${RUBY_VER}/ -I ${DIR}/bin/ -I ${RUBY_PLATFORM_DIR} -I ${DIR}/lib/ruby/site_ruby/${RUBY_VER}/ ${DIR}/bin/puppet apply --color false --modulepath=${modulepath} --show_diff --hiera_config=/tmp/cbsdpuppet/hiera.yaml --app_management --modulepath=/etc/puppetveil/code/environments/production/modules --log_level=debug"
#debug_args="debug"
echo "Module path: ${modulepath}"
#${DIR}/bin/ruby -I${DIR}/lib/ruby/vendor_ruby -I "${DIR}/lib/ruby/${RUBY_VER}/" -I "${DIR}/bin/" -I "${RUBY_PLATFORM_DIR}" -I "${DIR}/lib/ruby/site_ruby/${RUBY_VER}/" ${DIR}/bin/puppet apply $@ --color false --modulepath=${modulepath} --show_diff --hiera_config=/tmp/cbsdpuppet/hiera.yaml --modulepath=/etc/puppetveil/code/environments/production/modules --log_level=${error_level} --debug
${DIR}/bin/ruby -I${DIR}/lib/ruby/vendor_ruby -I \
"${DIR}/lib/ruby/${RUBY_VER}/" -I "${DIR}/bin/" -I "${RUBY_PLATFORM_DIR}" \
-I "${DIR}/lib/ruby/site_ruby/${RUBY_VER}/" \
${DIR}/bin/puppet apply $@ --show_diff --hiera_config=/tmp/cbsdpuppet/hiera.yaml --modulepath=${modulepath} --log_level=${debug_args} 2>&1 

echo "${DIR}/bin/puppet apply $@ --show_diff --hiera_config=/tmp/cbsdpuppet/hiera.yaml --modulepath=${modulepath} --log_level=${debug_args}"

[ "${debug_args}" = "debug" ] && read p
#|tee /tmp/out.txt

#read p
#--hiera_config=/tmp/cbsdpuppet/hiera.yaml
# 2>&1
